CREATE TABLE IF NOT EXISTS ITEMENTITY
(
    ID        UUID NOT NULL PRIMARY KEY,
    CREATEDAT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LOCK
(
    NAME_     VARCHAR(200) NOT NULL,
    IS_LOCKED boolean      NOT NULL,
    PRIMARY KEY (NAME_)
);

INSERT INTO LOCK(NAME_, IS_LOCKED)
values ('item_scheduler', false);

COMMIT;
